### ISSUE TITLE
Overrides WordPress's built-in image size/alignment features

### ISSUE THREAD

**Issue by joeldbirch** [aFarkas/wp-lazysizes#10]
Hello,

Love the plugin.

I find that images that are set to be a smaller width and are set to float with `.alignleft`, for example, will always be 100% width because they are wrapped in `intrinsic-ratio…` elements which are set to be 100%. I'm not sure what the answer is, but maybe the `.align…` class needs to be transfered to the intrinsic ratio wrapper element?

Cheers.

**Comment by TrilipuT** [comment]
Hello @joeldbirch, thanks for this issue.
I fix it just now. Could you test it and let me know if there are problems left?

**Comment by aFarkas** [comment]
This is huge, thought this is unfixable.
