### ISSUE TITLE
Update for Lazysizes 2.2.0?

### ISSUE THREAD

**Issue by stroblee** [aFarkas/wp-lazysizes#18]
Lazysizes is easily the best lazy loader around!  This is more a question that an issue...

Really hope there plans and aspirations to upgrade the plugin to use Lazysizes 2.2.0.  As @aFarkas mentions "... it could be heavily improved."

Being a hobbyist I have little experience and am neither a coder or developer - did come across these native WP image functions which may help simplify and improve the plugin https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/

This should really be part of the Wordpress core - the data-sizes:auto is far better than WP native responsiveness at serving the correct image.

Reapply appreciate all the work 👍

**Comment by TrilipuT** [comment]
Thanks for such nice words :)

I have updated to lazysizes 2.0. If you will have any other suggestions - let us know.

**Comment by stroblee** [comment]
Suer fast! Thank you very much Sir :)
