### ISSUE TITLE
Fatal error: line 47

### ISSUE THREAD

**Issue by jgraup** [aFarkas/wp-lazysizes#7]
I'm getting this on php 5.3. Never came up on 5.6.

`Fatal error: Cannot access self:: when no class scope is active in .../wp-content/plugins/wp-lazysizes/wp-lazysizes.php on line 47`

**Comment by TrilipuT** [comment]
Hi.
Thanks for this tip. I'm working on 5.4 and not tested it on 5.3. 
Will fix it soon.

**Comment by jgraup** [comment]
Just submitted a pull request. Seemed like that fixed the issue by just targeting the Class directly.

**Comment by jgraup** [comment]
BTW. I'm targeting 5.3 because my AWS EC2 servers seem to come stock with that lower version. While developing a theme I missed a few issues because they were ignored in 5.6.

**Comment by TrilipuT** [comment]
Yes, your fix works good. I will refactor code in future for supporting PHP 5.3+  version
